//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComhaltasWebApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class comhaltasTestEntities : DbContext
    {
        public comhaltasTestEntities()
            : base("name=comhaltasTestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin_users> Admin_users { get; set; }
        public virtual DbSet<Age_groups> Age_groups { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<Competition> Competitions { get; set; }
        public virtual DbSet<Entrant> Entrants { get; set; }
        public virtual DbSet<Entry> Entries { get; set; }
        public virtual DbSet<Instrument> Instruments { get; set; }
        public virtual DbSet<Result> Results { get; set; }
    }
}
